### PR TITLE
Address formatting bug introduced by #25

### LINKED ISSUE #46: Bug with PR#25 "Use i128 to represent integers"
Hi,

the PR https://github.com/butte-rs/butte/pull/25 has (exposed) a bug, for example:

```
table Hello {
    value: int64 = 0;
}
```

Now uses an `i128` for the default values in the Rust code even with the type being `i64`:

```Rust
fn add_value(&mut self, value: i64) {
    self.fbb.push_slot::<i64>(Hello::VT_VALUE, value, 0i128);
}
```

### PR DESCRIPTION
**Pull request by cpcloud**
Fixes #46.

### CODE REVIEW

**Comment by lovesegfault** [comment]
Fixed the merge conflict.

File: butte-build/src/codegen.rs [hunk 1]
```diff
@@ -190,14 +166,42 @@ fn to_type_token(
...
+    fn fmt_lit(&self, ty: impl Spanned + fmt::Display) -> Self::TokenType {
+        Self::TokenType::new(&format!("{}{}", self, ty), ty.span())
+    }
+}
+
+impl PrimitiveLiteralToken for ast::FloatingConstant {
+    type TokenType = syn::LitFloat;
+
+    fn fmt_lit(&self, ty: impl Spanned + fmt::Display) -> Self::TokenType {
+        Self::TokenType::new(&format!("{}{}", self, ty), ty.span())
```
Comment (reyk) [inline butte-build/src/codegen.rs]: The tests fail because it doesn't truncate the 64bit `FloatingConstant` to the target type.

The following unbreaks the tests, is there a better way to do this?

```suggestion
        let float_ty = format!("{}", ty);
        match float_ty.as_ref() {
            "f32" => Self::TokenType::new(&format!("{}{}", *self as f32, float_ty), ty.span()),
            _ => Self::TokenType::new(&format!("{}{}", self, float_ty), ty.span()),
        }
```

Comment (cpcloud) [reply butte-build/src/codegen.rs]: Yeah I had noticed this as well, but didn't a chance to come back to this. The fix looks ok if there's no better way to get the type out. I'll take a look for a bit and if nothing emerges I'll use this fix.

Comment (cpcloud) [reply butte-build/src/codegen.rs]: Alright, I ended up going with this fix (slightly rewritten, but semantically equivalent).

Comment (cpcloud) [reply butte-build/src/codegen.rs]: Thanks for this @reyk!

**Comment by cpcloud** [comment]
@lovesegfault @reyk @magnet This could use some more review if you're up for it.

File: butte-build/src/codegen.rs [hunk 2]
```diff
@@ -190,14 +166,48 @@ fn to_type_token(
...
     default_value: &ast::DefaultValue<'_>,
-) -> impl ToTokens {
+) -> impl ToTokens + fmt::Debug + ToString {
     match default_value {
         // Scalar field
-        ast::DefaultValue::Scalar(s) => s.to_token_stream(),
+        ast::DefaultValue::Scalar(s) => match s {
+            ast::Scalar::Integer(i) => i.fmt_lit(arg_ty.to_token_stream()).to_token_stream(),
+            ast::Scalar::Float(f) => f.fmt_lit(arg_ty.to_token_stream()).to_token_stream(),
+            ast::Scalar::Boolean(b) => b.to_token_stream(),
```
Comment (lovesegfault) [inline butte-build/src/codegen.rs:209]: Why is this pattern different only for `Boolean`?

**Comment by magnet** [comment]
> @lovesegfault @reyk @magnet This could use some more review if you're up for it.

Sorry, I've been pretty busy but I'm planning to return to butte for reviews & PRs next week(s) :)

File: butte-build/src/codegen.rs (hunk 2 above)
Comment (cpcloud) [reply butte-build/src/codegen.rs:209]: Because there's no need to do any special formatting for `Boolean` values, the syntax of Rust boolean literals is identical to the syntax of Flatbuffer boolean literals.

**Review by reyk — APPROVED** [review]
LGTM. I’ve also tested this MR with different schemas and it works fine.
